DEFAULT_MAX_FIELD_PCT = 0.15
DEFAULT_VARYING_LENGTH = True

JSON_OBJ_MAX_KEYS = 3
JSON_OBJ_MAX_VALS = 25

MYSQL_INT_MIN_MAX = {
    'MYSQL_MIN_TINYINT_SIGNED': -(2**7),
    'MYSQL_MAX_TINYINT_SIGNED': ~-(2**7),
    'MYSQL_MIN_SMALLINT_SIGNED': -(2**15),
    'MYSQL_MAX_SMALLINT_SIGNED': ~-(2**15),
    'MYSQL_MIN_MEDINT_SIGNED': -(2**23),
    'MYSQL_MAX_MEDINT_SIGNED': ~-(2*23),
    'MYSQL_MIN_INT_SIGNED': -(2**31),
    'MYSQL_MAX_INT_SIGNED': ~-(2**31),
    'MYSQL_MIN_BIGINT_SIGNED': -(2**63),
    'MYSQL_MAX_BIGINT_SIGNED': ~-(2*63),
    'MYSQL_MAX_TINYINT_UNSIGNED': ~-(2**8),
    'MYSQL_MAX_SMALLINT_UNSIGNED': ~-(2**16),
    'MYSQL_MAX_MEDINT_UNSIGNED': ~-(2**24),
    'MYSQL_MAX_INT_UNSIGNED': ~-(2**32),
    'MYSQL_MAX_BIGINT_UNSIGNED': ~-(2**64)
}
